# Theoritical Question:

### 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

### Purpose:
    Numpy is a fundamental library for numerical computation in python. It’s provides supports for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions.

### Advantages:
    • Efficient storage and manipulation of data using ndarray.

    • Faster optimization due to C-based backend.

    • Function for linear algebra, Statistics and Fourier transforms.

    • Supports vactorization, eliminating explicits loops.

    • Enables broadcasting for operation on arrays of different shapes.

### Enhancement of Python:
    It enhances Python’s ability to perform fast numerical operations, which is not nativvely optimized in standard lists.


### 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

    • np.mean(): Calculate the arithmetic mean of arrays elements.
    
    • Np.average(): Calculates the weighted average. You can supply weights.
    
### Use Case:
    • Use np.mean() When all values contribute equally.

    • Use np.average() when weights are assigned to values

In [20]:
import numpy as np

arr = np.array([1,2,3]) # Creates a NumPy array with elements 1, 2, 3

print(np.mean(arr))  # Calculates the mean: (1 + 2 + 3)/3 = 2.0

print(np.average(arr)) # Same result as mean when no weights are given: 2.0

print(np.average(arr,weights = [1,1,2])) # # Weighted average: (1×1 + 2×1 + 3×2) / (1 + 1 + 2) = (1 + 2 + 6)/4 = 2.25

2.0
2.0
2.25


### 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In [3]:
# 1-D array
import numpy as np

arr = np.array([1,2,3,4,5])
print("The Original array is:-->",arr)

# Reverse the array by slicing method
rev_arr = arr[::-1]
print("The reverse array is:--->",rev_arr)

The Original array is:--> [1 2 3 4 5]
The reverse array is:---> [5 4 3 2 1]


In [9]:
# 2-D array
arr_2D = np.array([[1,2,3],[4,5,6]])
print("The Original 2-D array is:--->\n",arr_2D)

# Row wise reverse
rev_arr_row = arr_2D[::-1]
print("After row wise reversed the array is:--->\n",rev_arr_row)

# column wised reversed
rev_arr_col = arr_2D[:,::-1]
print("After column wised revised the 2D array is:--->\n",rev_arr_col)

The Original 2-D array is:--->
 [[1 2 3]
 [4 5 6]]
After row wise reversed the array is:--->
 [[4 5 6]
 [1 2 3]]
After column wised revised the 2D array is:--->
 [[3 2 1]
 [6 5 4]]


### 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

#### Use .dtype:

In [26]:
import numpy as np

# Create  anumpy array
arr = np.array([1,2,3])

print("The data type of the numpy array is:- ",arr.dtype)

The data type of the numpy array is:-  int32


### Importance:
    • Efficient memory usage.
    • Fast operation (e.g., using int32 instead of float64 where appropriate)

### 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

#### Define ndarray and  Comparision to python lists:
    An ndarray is a multidimensional array object provided by Numpy.

#### Key Features:
    • Fixed-size,homogeneous type
    • Supports vectorized operations
    • Memory-efficient and faster than pyhton lists

#### Difference from Python lists:
    • Lists are heterogeneous and slower
    • Numpy arrays support broadcasting and multidimensional slicing.

### 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

#### Performance Benefites:
    • Numpy array use less memory than Python lists
    • Vectorized operations eliminates loops -> much faster
    • Leverages underlying C for execution -> highly optimized

### 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

In [16]:
import numpy as np

# Create 2 numpy array
a = np.array([1,2])
b = np.array([3,4])

print("Vertical Stack:-->\n",np.vstack((a,b))) # vstack represents Vertical Stack where elements or data add on row wise

print("\nHorizontal Stack:-->",np.hstack((a,b))) # hstack represents Horizontal stack where elements or data add on column wise

Vertical Stack:-->
 [[1 2]
 [3 4]]

Horizontal Stack:--> [1 2 3 4]


### 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

##### fliplr() vs flipud()
    • np.flipud(): Flip array up/down (reverse rows)
    • np.fliplr(): Flip arrays left/right (reverse columns)

In [21]:
# example
arr = np.array([[1,2],[3,4]])

print("Using fliplr():--->\n",np.fliplr(arr))
print("\nUsing flipud():--->\n",np.flipud(arr))

Using fliplr():--->
 [[2 1]
 [4 3]]

Using flipud():--->
 [[3 4]
 [1 2]]


### 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

array_split() Method
    Used to split arrays into sub-arrays.

### Syntax:
np.array(arr,n)  # where arr is the array name and n is the number of part too divied the array and n must be even number

#### Handles uneven splits:
    Distributes remaining elements as equally as possible.

### 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

### • Vectorization: Apply operations on arrays without using loops.

In [33]:
a = np.array([1,2])
b = np.array([3,4])

c = a + b # No any loops required on Vectorization

print(c)

[4 6]


### • Broadcasting:
    Numpy automatically expends smaller arrays to match the shape of larger ones.

### Benefits:
    • Cleaner code
    • Significantly faster than loops
    • Memory-efficient

# Practice Questions

# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np
arr = np.random.randint(1,100,size = (3,3))
print("Original Numpy array is-->\n",arr)
print("\n\nAfter interchange its rows and column the new array is--->\n",arr.T)

Original Numpy array is-->
 [[ 3 40 73]
 [31 91 72]
 [14 23 40]]


After interchange its rows and column the new array is--->
 [[ 3 31 14]
 [40 91 23]
 [73 72 40]]


# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [14]:
lis = []
for i in range(10):
    n = int(input(f"Enter the data from {str(i)} index:"))
    lis.append(n)

arr = np.array(lis)
print("Original 1D array is = ",arr)

# Reshape 2x5
arr_2D = arr.reshape(2,5)
print("\nAfter Reshape array into 2x5 then 2D array is--->\n",arr_2D)

# Reshape 5x2
new_arr_2D = arr_2D.reshape(5,2)
print("\nAfter Reshape the 2D array to 5x2 2D array is--->\n",new_arr_2D)

Enter the data from 0 index: 5
Enter the data from 1 index: 4
Enter the data from 2 index: 9
Enter the data from 3 index: 7
Enter the data from 4 index: 6
Enter the data from 5 index: 3
Enter the data from 6 index: 1
Enter the data from 7 index: 5
Enter the data from 8 index: 6
Enter the data from 9 index: 7


Original 1D array is =  [5 4 9 7 6 3 1 5 6 7]

After Reshape array into 2x5 then 2D array is--->
 [[5 4 9 7 6]
 [3 1 5 6 7]]

After Reshape the 2D array to 5x2 2D array is--->
 [[5 4]
 [9 7]
 [6 3]
 [1 5]
 [6 7]]


# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [41]:
arr = np.random.random_sample((4,4))
print("4x4 array is--->\n",arr)

padded_array = np.pad(arr,pad_width = 1,constant_values = 0)
print("\nAfter add the border with zero the new array is--->\n",padded_array)

4x4 array is--->
 [[0.3488027  0.60357982 0.90734668 0.5168685 ]
 [0.88220453 0.1750471  0.80999114 0.69191389]
 [0.73307396 0.78731604 0.29254918 0.63804864]
 [0.0022253  0.61947352 0.89606931 0.35720332]]

After add the border with zero the new array is--->
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.3488027  0.60357982 0.90734668 0.5168685  0.        ]
 [0.         0.88220453 0.1750471  0.80999114 0.69191389 0.        ]
 [0.         0.73307396 0.78731604 0.29254918 0.63804864 0.        ]
 [0.         0.0022253  0.61947352 0.89606931 0.35720332 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [4]:
arr = np.arange(10,60,5)

print("The array is = ",arr)

The array is =  [10 15 20 25 30 35 40 45 50 55]


# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.

In [52]:
arr = np.array(['Python','numpy','Pandas'])
# Uppercase
upper_arr = np.char.upper(arr)

# Lower case
lower_arr = np.char.lower(arr)

# Title case
title_arr = np.char.capitalize(arr)

print("Original array is = ",arr)
print("\nAfter convert each letter of array to Upeer case the new Upper case array is = ",upper_arr)
print("\nAfter convert each letter of array to Lower case the new Upper case array is = ",lower_arr)
print("\nAfter convert each letter of array to title case the new Upper case array is = ",title_arr)

Original array is =  ['Python' 'numpy' 'Pandas']

After convert each letter of array to Upeer case the new Upper case array is =  ['PYTHON' 'NUMPY' 'PANDAS']

After convert each letter of array to Lower case the new Upper case array is =  ['python' 'numpy' 'pandas']

After convert each letter of array to title case the new Upper case array is =  ['Python' 'Numpy' 'Pandas']


# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [57]:
sent = input("Enter your Sentence: ")
lis = sent.split()
arr = np.array(lis)
print("The array is--->\n",arr)

Enter your Sentence:  My name is Biswajit Adak


The array is--->
 ['My' 'name' 'is' 'Biswajit' 'Adak']


# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [64]:
# Create 2 2D array
arr1 = np.random.randint(1,10,size = (3,3))
arr2 = np.random.randint(1,10,size = (3,3))

# Print the 2 array
print("1st array is:--->\n",arr1)
print("\n2nd array is--->\n",arr2)

# Addition
sum = arr1 + arr2 # or np.add(arr1,arr2)

# Subtraction
sub = arr1 - arr2 # or np.subtract(arr1,arr2)

# Multiplication
mult = arr1 @ arr2 # or np.dot(arr1,arr2)

# Divition
div = arr1/arr2 # or np.divied(arr1,arr2)

# print all arithmetic operation over 2 arrays
print("\nThe Sum of 2 array is--->\n",sum)
print("\nThe subtraction of 2 array is--->\n",sub)
print("\nThe elemet wise multiplication(matrix multiplication) of 2 array is---->\n",mult)
print("\nThe divition of 2 array is--->\n",div)

1st array is:--->
 [[9 7 1]
 [2 4 7]
 [9 7 9]]

2nd array is--->
 [[7 6 7]
 [5 7 9]
 [2 8 4]]

The Sum of 2 array is--->
 [[16 13  8]
 [ 7 11 16]
 [11 15 13]]

The subtraction of 2 array is--->
 [[ 2  1 -6]
 [-3 -3 -2]
 [ 7 -1  5]]

The elemet wise multiplication of 2 array is---->
 [[100 111 130]
 [ 48  96  78]
 [116 175 162]]

The divition of 2 array is--->
 [[1.28571429 1.16666667 0.14285714]
 [0.4        0.57142857 0.77777778]
 [4.5        0.875      2.25      ]]


# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [69]:
# create 5x5 identity matrix
iden_arr = np.eye(5,dtype = int)
print("The Identity matrix is--->\n",iden_arr)

# Print diagonal elemet
diagonal_element = np.diagonal(iden_arr)
print("\nThe Diagonal element of the identity matric is-->\n",diagonal_element)

The Identity matrix is--->
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

The Diagonal element of the identity matric is-->
 [1 1 1 1 1]


# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers inthis array.

In [104]:
# Create function to check the the number is prime or not
def calculate_prime_number(arr):
    lis = []
    for i in arr:
        flag = 0
        for j in range(2,(i//2)+1):
            if i % j == 0:
                flag = 1
                break
        if flag == 0:
            lis.append(i)
    return lis

# Generate a numpy array of 100 random integer between 1 and 1000
arr = np.random.randint(1,1000,size = (1,100)) # it's return 2D array4

# Convert into 1D array
arr = arr.flatten()

print("Original array are--->\n",arr)

prime_num = calculate_prime_number(arr)
prime_arr = np.array(prime_num)
print("\nPrime number are-->",prime_arr)

Original array are--->
 [770 968 734 541 556 192 186 605 992 435  47 669 349  23 139  94 579 544
  73 338 752 409 143 932 575 840 364 107 662 265 520 264 207 848 187 523
 151 532 251 780 505 738 685 166 244 566 790 137 264 144 363 946 104 242
 391 311 256 375 607 765 427 627 266 963 920 177 393  47 276 640 122 414
 842 617 676 334 300 405 606   1 705 111 509 573 139  42 431 247 165 370
 675 189  24 772 576  90 891 676  94 136]

Prime number are--> [541  47 349  23 139  73 409 107 523 151 251 137 311 607  47 617   1 509
 139 431]


# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weeklyaverages.

In [5]:
daily_temperature = np.array([30,31,32,36,34,32,31,32,35,36,
                             35,37,32,31,38,39,35,34,32,34,
                             32,31,30,30,35,34,36,32])
weekly_temperature  = daily_temperature.reshape(4,7)

# calculate average temperature
avg_temp = weekly_temperature.mean(axis = 1)
avg_temp

array([32.28571429, 34.        , 34.85714286, 32.57142857])